version: 2
updates:
  # Enable version updates for yarn
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '*storybook*'
